/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerData { 'fields' : Array<[string, string]> }
export interface CustomerWithId {
  'id' : string,
  'fields' : Array<[string, string]>,
}
export interface DropdownOption {
  'id' : string,
  'optionLabel' : string,
  'color' : string,
}
export interface FieldDef {
  'id' : string,
  'order' : bigint,
  'fieldLabel' : string,
  'required' : boolean,
  'fieldType' : string,
}
export interface PlanData {
  'status' : string,
  'dateStr' : string,
  'name' : string,
  'plan' : string,
  'installment' : string,
  'mobile' : string,
}
export interface PlanOption {
  'id' : string,
  'optionLabel' : string,
  'color' : string,
}
export interface PlanWithId {
  'id' : string,
  'status' : string,
  'dateStr' : string,
  'name' : string,
  'plan' : string,
  'installment' : string,
  'daysCount' : bigint,
  'mobile' : string,
}
export interface Settings { 'ghRgaOptions' : Array<DropdownOption> }
export interface TagOption {
  'id' : string,
  'optionLabel' : string,
  'color' : string,
}
export interface UserInfo { 'userName' : string, 'mobile' : string }
export interface _SERVICE {
  'addCustomer' : ActorMethod<[string, CustomerData], string>,
  'addPlan' : ActorMethod<[string, PlanData], string>,
  'createUser' : ActorMethod<[string, string], boolean>,
  'deleteAllPlans' : ActorMethod<[string], boolean>,
  'deleteCustomer' : ActorMethod<[string, string], boolean>,
  'deletePlan' : ActorMethod<[string, string], boolean>,
  'deleteUser' : ActorMethod<[string], boolean>,
  'generateOtp' : ActorMethod<[string], string>,
  'getAllCustomers' : ActorMethod<[string], Array<CustomerWithId>>,
  'getAllCustomersForAdmin' : ActorMethod<
    [],
    Array<[string, Array<CustomerWithId>]>
  >,
  'getAllPlans' : ActorMethod<[string], Array<PlanWithId>>,
  'getAllPlansForAdmin' : ActorMethod<[], Array<[string, Array<PlanWithId>]>>,
  'getColorTheme' : ActorMethod<[], string>,
  'getCustomer' : ActorMethod<[string, string], [] | [CustomerWithId]>,
  'getCustomerCount' : ActorMethod<[string], bigint>,
  'getFieldDefinitions' : ActorMethod<[], Array<FieldDef>>,
  'getPlan' : ActorMethod<[string, string], [] | [PlanWithId]>,
  'getPlanOptions' : ActorMethod<[], Array<PlanOption>>,
  'getRegisteredUsers' : ActorMethod<[], Array<UserInfo>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getTagOptions' : ActorMethod<[], Array<TagOption>>,
  'getUserName' : ActorMethod<[string], [] | [string]>,
  'updateColorTheme' : ActorMethod<[string], boolean>,
  'updateCustomer' : ActorMethod<[string, string, CustomerData], boolean>,
  'updateFieldDefinitions' : ActorMethod<[Array<FieldDef>], boolean>,
  'updatePlan' : ActorMethod<[string, string, PlanData], boolean>,
  'updatePlanOptions' : ActorMethod<[Array<PlanOption>], boolean>,
  'updatePlanStatus' : ActorMethod<[string, string, string], boolean>,
  'updateSettings' : ActorMethod<[Settings], boolean>,
  'updateTagOptions' : ActorMethod<[Array<TagOption>], boolean>,
  'verifyOtp' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];