/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Customer = IDL.Record({
  'tag' : IDL.Text,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'ghRga' : IDL.Text,
  'address' : IDL.Text,
});
export const CustomerWithId = IDL.Record({
  'id' : IDL.Nat,
  'tag' : IDL.Text,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'ghRga' : IDL.Text,
  'address' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([Customer], [IDL.Nat], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerWithId)], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getSettings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'updateCustomer' : IDL.Func([IDL.Nat, Customer], [], []),
  'updateSettings' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Customer = IDL.Record({
    'tag' : IDL.Text,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'ghRga' : IDL.Text,
    'address' : IDL.Text,
  });
  const CustomerWithId = IDL.Record({
    'id' : IDL.Nat,
    'tag' : IDL.Text,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'ghRga' : IDL.Text,
    'address' : IDL.Text,
  });
  return IDL.Service({
    'addCustomer' : IDL.Func([Customer], [IDL.Nat], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(CustomerWithId)], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getSettings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'updateCustomer' : IDL.Func([IDL.Nat, Customer], [], []),
    'updateSettings' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
