/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';

export interface Customer {
  'tag' : string,
  'name' : string,
  'mobileNumber' : string,
  'ghRga' : string,
  'address' : string,
}
export interface CustomerWithId {
  'id' : bigint,
  'tag' : string,
  'name' : string,
  'mobileNumber' : string,
  'ghRga' : string,
  'address' : string,
}
export interface TagOption {
  'tagLabel' : string,
  'tagColor' : string,
}
export interface _SERVICE {
  'addCustomer' : ActorMethod<[Customer], bigint>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<CustomerWithId>>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getSettings' : ActorMethod<[], Array<string>>,
  'getTagOptions' : ActorMethod<[], Array<TagOption>>,
  'updateCustomer' : ActorMethod<[bigint, Customer], undefined>,
  'updateSettings' : ActorMethod<[Array<string>], undefined>,
  'updateTagOptions' : ActorMethod<[Array<TagOption>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
