/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomField = IDL.Record({
  'fieldName' : IDL.Text,
  'fieldValue' : IDL.Text,
});
export const Customer = IDL.Record({
  'tag' : IDL.Text,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'isHighlighted' : IDL.Bool,
  'customFields' : IDL.Vec(CustomField),
  'ghRga' : IDL.Text,
  'address' : IDL.Text,
});
export const Plan = IDL.Record({
  'name' : IDL.Text,
  'plan' : IDL.Text,
  'dateEntry' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'installment' : IDL.Text,
  'billRefundStatus' : IDL.Text,
});
export const PlanWithId = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'plan' : IDL.Text,
  'dateEntry' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'installment' : IDL.Text,
  'daysCount' : IDL.Nat,
  'billRefundStatus' : IDL.Text,
});
export const CustomerWithId = IDL.Record({
  'id' : IDL.Nat,
  'tag' : IDL.Text,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'isHighlighted' : IDL.Bool,
  'customFields' : IDL.Vec(CustomField),
  'ghRga' : IDL.Text,
  'address' : IDL.Text,
});
export const UserCustomerData = IDL.Record({
  'userMobile' : IDL.Text,
  'customers' : IDL.Vec(CustomerWithId),
});
export const UserPlanData = IDL.Record({
  'userMobile' : IDL.Text,
  'plans' : IDL.Vec(PlanWithId),
});
export const FieldDefinition = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'fieldLabel' : IDL.Text,
  'fieldType' : IDL.Text,
});
export const User = IDL.Record({
  'userName' : IDL.Text,
  'createdAt' : IDL.Int,
  'mobile' : IDL.Text,
});
export const TagOption = IDL.Record({
  'tagColor' : IDL.Text,
  'tagLabel' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCustomer' : IDL.Func([IDL.Text, Customer], [IDL.Nat], []),
  'addPlan' : IDL.Func([IDL.Text, Plan], [PlanWithId], []),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deletePlan' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'deleteUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
      [],
    ),
  'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllCustomers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CustomerWithId)],
      ['query'],
    ),
  'getAllCustomersForAdmin' : IDL.Func(
      [],
      [IDL.Vec(UserCustomerData)],
      ['query'],
    ),
  'getAllPlans' : IDL.Func([IDL.Text], [IDL.Vec(PlanWithId)], ['query']),
  'getAllPlansForAdmin' : IDL.Func([], [IDL.Vec(UserPlanData)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getColorTheme' : IDL.Func([], [IDL.Text], ['query']),
  'getCustomer' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(CustomerWithId)],
      ['query'],
    ),
  'getCustomerCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getFieldDefinitions' : IDL.Func([], [IDL.Vec(FieldDefinition)], ['query']),
  'getPlan' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(PlanWithId)], ['query']),
  'getPlanOptions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRegisteredUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTagOptions' : IDL.Func([], [IDL.Vec(TagOption)], ['query']),
  'getUserName' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'updateColorTheme' : IDL.Func([IDL.Text], [], []),
  'updateCustomer' : IDL.Func([IDL.Text, IDL.Nat, Customer], [IDL.Bool], []),
  'updateFieldDefinitions' : IDL.Func([IDL.Vec(FieldDefinition)], [], []),
  'updatePlan' : IDL.Func([IDL.Text, IDL.Nat, Plan], [IDL.Bool], []),
  'updatePlanOptions' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updatePlanStatus' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Bool], []),
  'updateSettings' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateTagOptions' : IDL.Func([IDL.Vec(TagOption)], [], []),
  'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomField = IDL.Record({
    'fieldName' : IDL.Text,
    'fieldValue' : IDL.Text,
  });
  const Customer = IDL.Record({
    'tag' : IDL.Text,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'isHighlighted' : IDL.Bool,
    'customFields' : IDL.Vec(CustomField),
    'ghRga' : IDL.Text,
    'address' : IDL.Text,
  });
  const Plan = IDL.Record({
    'name' : IDL.Text,
    'plan' : IDL.Text,
    'dateEntry' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'installment' : IDL.Text,
    'billRefundStatus' : IDL.Text,
  });
  const PlanWithId = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'plan' : IDL.Text,
    'dateEntry' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'installment' : IDL.Text,
    'daysCount' : IDL.Nat,
    'billRefundStatus' : IDL.Text,
  });
  const CustomerWithId = IDL.Record({
    'id' : IDL.Nat,
    'tag' : IDL.Text,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'isHighlighted' : IDL.Bool,
    'customFields' : IDL.Vec(CustomField),
    'ghRga' : IDL.Text,
    'address' : IDL.Text,
  });
  const UserCustomerData = IDL.Record({
    'userMobile' : IDL.Text,
    'customers' : IDL.Vec(CustomerWithId),
  });
  const UserPlanData = IDL.Record({
    'userMobile' : IDL.Text,
    'plans' : IDL.Vec(PlanWithId),
  });
  const FieldDefinition = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'fieldLabel' : IDL.Text,
    'fieldType' : IDL.Text,
  });
  const User = IDL.Record({
    'userName' : IDL.Text,
    'createdAt' : IDL.Int,
    'mobile' : IDL.Text,
  });
  const TagOption = IDL.Record({
    'tagColor' : IDL.Text,
    'tagLabel' : IDL.Text,
  });
  
  return IDL.Service({
    'addCustomer' : IDL.Func([IDL.Text, Customer], [IDL.Nat], []),
    'addPlan' : IDL.Func([IDL.Text, Plan], [PlanWithId], []),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deletePlan' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'deleteUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'message' : IDL.Text })],
        [],
      ),
    'generateOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllCustomers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CustomerWithId)],
        ['query'],
      ),
    'getAllCustomersForAdmin' : IDL.Func(
        [],
        [IDL.Vec(UserCustomerData)],
        ['query'],
      ),
    'getAllPlans' : IDL.Func([IDL.Text], [IDL.Vec(PlanWithId)], ['query']),
    'getAllPlansForAdmin' : IDL.Func([], [IDL.Vec(UserPlanData)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getColorTheme' : IDL.Func([], [IDL.Text], ['query']),
    'getCustomer' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(CustomerWithId)],
        ['query'],
      ),
    'getCustomerCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getFieldDefinitions' : IDL.Func([], [IDL.Vec(FieldDefinition)], ['query']),
    'getPlan' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(PlanWithId)], ['query']),
    'getPlanOptions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRegisteredUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTagOptions' : IDL.Func([], [IDL.Vec(TagOption)], ['query']),
    'getUserName' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'updateColorTheme' : IDL.Func([IDL.Text], [], []),
    'updateCustomer' : IDL.Func([IDL.Text, IDL.Nat, Customer], [IDL.Bool], []),
    'updateFieldDefinitions' : IDL.Func([IDL.Vec(FieldDefinition)], [], []),
    'updatePlan' : IDL.Func([IDL.Text, IDL.Nat, Plan], [IDL.Bool], []),
    'updatePlanOptions' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updatePlanStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateSettings' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateTagOptions' : IDL.Func([IDL.Vec(TagOption)], [], []),
    'verifyOtp' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };