/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TagOption {
    id: string;
    optionLabel: string;
    color: string;
}
export interface Settings {
    ghRgaOptions: Array<DropdownOption>;
}
export interface CustomerWithId {
    id: string;
    fields: Array<[string, string]>;
}
export interface DropdownOption {
    id: string;
    optionLabel: string;
    color: string;
}
export interface PlanWithId {
    id: string;
    status: string;
    dateStr: string;
    name: string;
    plan: string;
    installment: string;
    daysCount: bigint;
    mobile: string;
}
export interface CustomerData {
    fields: Array<[string, string]>;
}
export interface FieldDef {
    id: string;
    order: bigint;
    fieldLabel: string;
    required: boolean;
    fieldType: string;
}
export interface PlanData {
    status: string;
    dateStr: string;
    name: string;
    plan: string;
    installment: string;
    mobile: string;
}
export interface UserInfo {
    userName: string;
    mobile: string;
}
export interface PlanOption {
    id: string;
    optionLabel: string;
    color: string;
}
export interface backendInterface {
    addCustomer(mobile: string, data: CustomerData): Promise<string>;
    addPlan(mobile: string, plan: PlanData): Promise<string>;
    createUser(mobile: string, userName: string): Promise<boolean>;
    deleteAllPlans(mobile: string): Promise<boolean>;
    deleteCustomer(mobile: string, id: string): Promise<boolean>;
    deletePlan(mobile: string, id: string): Promise<boolean>;
    deleteUser(mobile: string): Promise<boolean>;
    generateOtp(mobile: string): Promise<string>;
    getAllCustomers(mobile: string): Promise<Array<CustomerWithId>>;
    getAllCustomersForAdmin(): Promise<Array<[string, Array<CustomerWithId>]>>;
    getAllPlans(mobile: string): Promise<Array<PlanWithId>>;
    getAllPlansForAdmin(): Promise<Array<[string, Array<PlanWithId>]>>;
    getColorTheme(): Promise<string>;
    getCustomer(mobile: string, id: string): Promise<CustomerWithId | null>;
    getCustomerCount(mobile: string): Promise<bigint>;
    getFieldDefinitions(): Promise<Array<FieldDef>>;
    getPlan(mobile: string, id: string): Promise<PlanWithId | null>;
    getPlanOptions(): Promise<Array<PlanOption>>;
    getRegisteredUsers(): Promise<Array<UserInfo>>;
    getSettings(): Promise<Settings>;
    getTagOptions(): Promise<Array<TagOption>>;
    getUserName(mobile: string): Promise<string | null>;
    updateColorTheme(theme: string): Promise<boolean>;
    updateCustomer(mobile: string, id: string, data: CustomerData): Promise<boolean>;
    updateFieldDefinitions(fields: Array<FieldDef>): Promise<boolean>;
    updatePlan(mobile: string, id: string, plan: PlanData): Promise<boolean>;
    updatePlanOptions(options: Array<PlanOption>): Promise<boolean>;
    updatePlanStatus(mobile: string, id: string, status: string): Promise<boolean>;
    updateSettings(s: Settings): Promise<boolean>;
    updateTagOptions(options: Array<TagOption>): Promise<boolean>;
    verifyOtp(mobile: string, otp: string): Promise<boolean>;
}
import type { CustomerWithId as _CustomerWithId, PlanWithId as _PlanWithId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCustomer(arg0: string, arg1: CustomerData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1);
            return result;
        }
    }
    async addPlan(arg0: string, arg1: PlanData): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlan(arg0, arg1);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1);
            return result;
        }
    }
    async deleteAllPlans(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllPlans(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllPlans(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0, arg1);
            return result;
        }
    }
    async deletePlan(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlan(arg0, arg1);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async generateOtp(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateOtp(arg0);
            return result;
        }
    }
    async getAllCustomers(arg0: string): Promise<Array<CustomerWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers(arg0);
            return result;
        }
    }
    async getAllCustomersForAdmin(): Promise<Array<[string, Array<CustomerWithId>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomersForAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomersForAdmin();
            return result;
        }
    }
    async getAllPlans(arg0: string): Promise<Array<PlanWithId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlans(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlans(arg0);
            return result;
        }
    }
    async getAllPlansForAdmin(): Promise<Array<[string, Array<PlanWithId>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlansForAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlansForAdmin();
            return result;
        }
    }
    async getColorTheme(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getColorTheme();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getColorTheme();
            return result;
        }
    }
    async getCustomer(arg0: string, arg1: string): Promise<CustomerWithId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0, arg1);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0, arg1);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerCount(arg0);
            return result;
        }
    }
    async getFieldDefinitions(): Promise<Array<FieldDef>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFieldDefinitions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFieldDefinitions();
            return result;
        }
    }
    async getPlan(arg0: string, arg1: string): Promise<PlanWithId | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlan(arg0, arg1);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlan(arg0, arg1);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlanOptions(): Promise<Array<PlanOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanOptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanOptions();
            return result;
        }
    }
    async getRegisteredUsers(): Promise<Array<UserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegisteredUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegisteredUsers();
            return result;
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getTagOptions(): Promise<Array<TagOption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTagOptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTagOptions();
            return result;
        }
    }
    async getUserName(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserName(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserName(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateColorTheme(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateColorTheme(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateColorTheme(arg0);
            return result;
        }
    }
    async updateCustomer(arg0: string, arg1: string, arg2: CustomerData): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async updateFieldDefinitions(arg0: Array<FieldDef>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFieldDefinitions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFieldDefinitions(arg0);
            return result;
        }
    }
    async updatePlan(arg0: string, arg1: string, arg2: PlanData): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlan(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlan(arg0, arg1, arg2);
            return result;
        }
    }
    async updatePlanOptions(arg0: Array<PlanOption>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlanOptions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlanOptions(arg0);
            return result;
        }
    }
    async updatePlanStatus(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlanStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlanStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSettings(arg0: Settings): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async updateTagOptions(arg0: Array<TagOption>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTagOptions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTagOptions(arg0);
            return result;
        }
    }
    async verifyOtp(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyOtp(arg0, arg1);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerWithId]): CustomerWithId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlanWithId]): PlanWithId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
